# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

# IMPORTANT: Specify your personal configuration here. After having done so, run the following command to avoid git committing the file with your personal configurations:
# git update-index --skip-worktree FILENAME
# and if you want to track the changes again use this command:
# git update-index --no-skip-worktree FILENAME
# See also: https://stackoverflow.com/questions/13630849/git-difference-between-assume-unchanged-and-skip-worktree#

remote:
  ssh: "zecm"
  path: "scratch/pypsa-de"

run:
  prefix: 20250430_low_res
  name:
  - 8Gt_Bal_v3
  - reference  # reference scenario is necessary for get_FEC_reference (used in clever)
  - clever
  - ref-constr50  # based on reference scenario, each country has 50% of their 2020 space requirement in 2050
  - ref-constr25
#  - ref-constr20
#  - ref-constr15
#  - ref-constr10
#  - ref-constr05
  - ref-constr01
  - cle-constr50
  - cle-constr25
  - cle-constr01
  scenarios:
    enable: true
    manual_file: config/scenarios.personal_jeckstadt.yaml
    file: config/scenarios.automated.yaml
  shared_resources:
    policy: base #stops recalculating
    exclude:
    - existing_heating.csv   # specify files which should not be shared between scenarios
    - costs
    - retrieve_cost   # This is necessary to save retrieve_cost_data_{year}.log in the correct folder
    - industry_sector_ratios
    - build_industry_sector_ratios   # This is necessary to save build_industry_sector_ratios_data.log in the correct folder
    - modify_existing_heating

iiasa_database:
  db_name: ariadne
  leitmodelle:
    general: REMIND-EU v1.1
    buildings: REMod v1.0
    transport: REMIND-EU v1.1
    transport_stock: DLR-VECTOR21
    industry: FORECAST v1.0
  scenarios:
  - 8Gt_Bal_v3
  #- 8Gt_Elec_v3  # unused scenario
  #- 8Gt_H2_v3  # unused scenario
  reference_scenario: 8Gt_Bal_v3
  region: Deutschland

costs:
  horizon: "mean"
  NEP: 2023
  transmission: "overhead" # either overhead line ("overhead") or underground cable ("underground")

scenario:
  clusters:
    - adm  # administrative setting
    #- 30  # current options: 27, 49
  planning_horizons:  # note: only works with 2020 as starting year due to hard-coded get_FEC_reference.
    - 2020
    - 2030
    - 2040
    - 2050

countries: ['AT', 'BE', 'CH', 'CZ', 'DE', 'DK', 'FR', 'GB', 'LU', 'NL', 'NO', 'PL', 'SE', 'ES', 'IT']

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#snapshots
snapshots:
  start: "2019-01-01"
  end: "2020-01-01"
  inclusive: 'left'

enable:
  retrieve: false
  retrieve_databundle: false
  retrieve_cost_data: false
  build_cutout: false
  retrieve_cutout: false
  custom_busmap: false
  drop_leap_day: true

electricity:
  extendable_carriers:
    Generator: [solar, onwind, offwind-ac, offwind-dc, OCGT, CCGT] #solar-hsat, offwind-float

  conventional_carriers: [ nuclear, oil, OCGT, CCGT, coal, lignite, geothermal, biomass ]
  renewable_carriers: [ solar, onwind, offwind-ac, offwind-dc, hydro ] #  solar-hsat,  offwind-float,

  transmission_limit: v1.1  # 10%

sector:
  industry: true
  agriculture: true
  gas_network: false
  regional_gas_demand: true
  cluster_heat_buses: false
  biomass_spatial: true # Transport deactivated by changing code in scripts/prepare_sector_network.py:3585

clustering:
  mode: administrative
  administrative:
    level: 0
    DE: 1
    CH: 1

  temporal:
    resolution_elec: false
    #resolution_sector: 2190seg #169H  # Woche, 2190seg -> ca. 4stündlich lange segmente
    resolution_sector: 169H

solving:
  mem_mb: 100000 #memory in MB; 20 GB enough for 50+B+I+H2; 100 GB for 181+B+I+H2
  memory_logging_frequency: 30 # in seconds
  runtime: 24h #runtime in humanfriendly style https://humanfriendly.readthedocs.io/en/latest/
  constraints:
    # boundary condition of maximum volumes
    limits_volume_max:
      # constrain electricity import in TWh
      electricity_import:
        DE:
          2020: -20
          2025: 0
          2030: 0
          2035: 40
          2040: 80
          2045: 125
      electrolysis:
        DE:
          2020: 0
          2025: 5
          2030: 45
          2035: 130
          2040: 215
          2045: 300
      h2_derivate_import:
        DE:
          2020: 0
          2025: 0
          2030: 10
          2035: 105
          2040: 200
          2045: 300
      h2_import:
        DE:
          2020: 0
          2025: 5
          2030: 15
          2035: 115
          2040: 220
          2045: 325
    limits_volume_min:
      electrolysis:
        DE:
          2020: 0
          2025: 0
          2030: 0
          2035: 0
          2040: 0
          2045: 0
    limits_capacity_min:
      Link:
        H2 Electrolysis:
          DE:
            2030: 5

industry:
  steam_biomass_fraction: 0.4
  steam_hydrogen_fraction: 0.3
  steam_electricity_fraction: 0.3


clever: false  # for sufficiency scenario, set in scenarios


land_use_module:
  enable: true
  types:
    DLU:  # direct land use
      power_specific_generators: [onwind, solar]  # space_req_pu is taken from DEA-Dataset if not overwritten below.
      overwrite_values:  # unit: m2/MW
    #    onwind:
    #      2020: 1020.0
    #      2030: 1030.0
    #      2040: 1040.0
      energy_specific_generators:  # unit: m2/MWh. space_req_pu is manually defined here
        unsustainable solid biomass: 434.8  # woody biocrops
        unsustainable biogas: 120.5  # digestible biocrops
        unsustainable bioliquids: 120.5  # oily biocrops
      constraint:
        enable: false
        negative_additional: error  # possible options: warning, error
#        max_limit:  # unit in m²
#          EU:  # for all countries and 5% of that area
#            2020: 171e9
#            2030: 171e9
#            2040: 171e9
#            2045: 171e9
#            2050: 171e9
#          DE:
#            2020: 17.9e9  # 5% of Germany area
#            2030: 17.9e9
#            2040: 17.9e9
#            2045: 17.9e9
#            2050: 17.9e9
#          FR:
#            2020: 27.3e9  # 5% of France area
#            2030: 27.3e9
#            2040: 27.3e9
#            2050: 27.3e9
    dist:  # disturbed area
      power_specific_generators: [solar]  # space_req_pu is taken from DEA-Dataset if not overwritten below.
      overwrite_values:  # unit: m2/MW
          onwind: # from DEA
            2020: 366519.143
            2030: 307876.080
            2040: 279887.346
            2050: 256563.400
      energy_specific_generators: # unit: m2/MWh. space_req_pu is manually defined here
        unsustainable solid biomass: 434.8  # woody biocrops
        unsustainable biogas: 120.5  # digestible biocrops
        unsustainable bioliquids: 120.5  # oily biocrops
      constraint:
        enable: false


biomass:  # reference biomass potentials for all scenarios. 8Gt_Bal_v3 overwritten with default in scenario.
  share_unsustainable_use_retained:
    2020: 1
    2025: 1
    2030: 1
    2035: 1
    2040: 1
    2045: 1
    2050: 1
  share_sustainable_potential_available:
    2020: 0
    2025: 0.33
    2030: 0.66
    2035: 1
    2040: 1
    2045: 1
    2050: 1
  share_unsustainable_min:
    2020: 1
    2025: 0.66
    2030: 0.33
    2035: 0
    2040: 0
    2045: 0
    2050: 0

