# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT


8Gt_Bal_v3:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG
  solving:
    constraints:
      co2_budget_national:
        2020:
          DE: 0.668
        2025:
          DE: 0.521
        2030:
          DE: 0.351
        2035:
          DE: 0.217
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.046

  sector:
    biomass_transported_p_nom: 10000  # default value

    aviation_demand_factor:
      2020: 1.0
      2025: 0.9321
      2030: 0.8687
      2035: 0.7719
      2040: 0.6926
      2045: 0.6417
  clever: false

  land_use_module:
    types:
      DLU:
        constraint:
          enable: false

  biomass: # from config.default
    share_unsustainable_use_retained:
      2020: 1
      2025: 0.66
      2030: 0.33
      2035: 0
      2040: 0
      2045: 0
      2050: 0
    share_sustainable_potential_available:
      2020: 0
      2025: 0.33
      2030: 0.66
      2035: 1
      2040: 1
      2045: 1
      2050: 1
    share_unsustainable_min: # share of share_unsustainable_use_retained as minimum use
      2020: 1
      2025: 1
      2030: 1
      2035: 1
      2040: 1
      2045: 1
      2050: 1




reference:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG
  solving:
    constraints:
      co2_budget_national:
        2020:
          DE: 0.668
        2025:
          DE: 0.521
        2030:
          DE: 0.351
        2035:
          DE: 0.217
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.046


  clever: false

  land_use_module:
    types:
      DLU:
        constraint:
          enable: false



  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9321
      2030: 0.8687
      2035: 0.7719
      2040: 0.6926
      2045: 0.6417
clever:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG
  solving:
    constraints:
      co2_budget_national:
        2020:
          DE: 0.668
        2025:
          DE: 0.521
        2030:
          DE: 0.351
        2035:
          DE: 0.217
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.046

  clever: true

  land_use_module:
    types:
      DLU:
        constraint:
          enable: false



  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9321
      2030: 0.8687
      2035: 0.7719
      2040: 0.6926
      2045: 0.6417
ref-constr50:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG
  solving:
    constraints:
      co2_budget_national:
        2020:
          DE: 0.668
        2025:
          DE: 0.521
        2030:
          DE: 0.351
        2035:
          DE: 0.217
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.046
  clever: false
  land_use_module:
    types:
      DLU:
        constraint:
          enable: true
          max_limit:
            AT:
              2030: 20407.0e6
              2040: 16325.6e6
              2050: 12244.2e6
            BE:
              2030: 5902.4e6
              2040: 4721.9e6
              2050: 3541.4e6
            CH:
              2030: 34.1e6
              2040: 27.3e6
              2050: 20.5e6
            CZ:
              2030: 15231.0e6
              2040: 12184.8e6
              2050: 9138.6e6
            DE:
              2030: 67475.5e6
              2040: 53980.4e6
              2050: 40485.3e6
            DK:
              2030: 6770.0e6
              2040: 5416.0e6
              2050: 4062.0e6
            ES:
              2030: 24107.4e6
              2040: 19285.9e6
              2050: 14464.5e6
            FR:
              2030: 47851.9e6
              2040: 38281.5e6
              2050: 28711.1e6
            GB:
              2030: 23900.2e6
              2040: 19120.1e6
              2050: 14340.1e6
            IT:
              2030: 34444.1e6
              2040: 27555.3e6
              2050: 20666.5e6
            LU:
              2030: 503.4e6
              2040: 402.7e6
              2050: 302.0e6
            NL:
              2030: 8692.8e6
              2040: 6954.2e6
              2050: 5215.7e6
            NO:
              2030: 4125.5e6
              2040: 3300.4e6
              2050: 2475.3e6
            PL:
              2030: 39492.5e6
              2040: 31594.0e6
              2050: 23695.5e6
            SE:
              2030: 40670.4e6
              2040: 32536.3e6
              2050: 24402.2e6

  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9321
      2030: 0.8687
      2035: 0.7719
      2040: 0.6926
      2045: 0.6417
ref-constr25:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG
  solving:
    constraints:
      co2_budget_national:
        2020:
          DE: 0.668
        2025:
          DE: 0.521
        2030:
          DE: 0.351
        2035:
          DE: 0.217
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.046
  clever: false
  land_use_module:
    types:
      DLU:
        constraint:
          enable: true
          max_limit:
            AT:
              2030: 18366.3e6
              2040: 12244.2e6
              2050: 6122.1e6
            BE:
              2030: 5312.1e6
              2040: 3541.4e6
              2050: 1770.7e6
            CH:
              2030: 30.7e6
              2040: 20.5e6
              2050: 10.2e6
            CZ:
              2030: 13707.9e6
              2040: 9138.6e6
              2050: 4569.3e6
            DE:
              2030: 60727.9e6
              2040: 40485.3e6
              2050: 20242.6e6
            DK:
              2030: 6093.0e6
              2040: 4062.0e6
              2050: 2031.0e6
            ES:
              2030: 21696.7e6
              2040: 14464.5e6
              2050: 7232.2e6
            FR:
              2030: 43066.7e6
              2040: 28711.1e6
              2050: 14355.6e6
            GB:
              2030: 21510.2e6
              2040: 14340.1e6
              2050: 7170.1e6
            IT:
              2030: 30999.7e6
              2040: 20666.5e6
              2050: 10333.2e6
            LU:
              2030: 453.1e6
              2040: 302.0e6
              2050: 151.0e6
            NL:
              2030: 7823.5e6
              2040: 5215.7e6
              2050: 2607.8e6
            NO:
              2030: 3712.9e6
              2040: 2475.3e6
              2050: 1237.6e6
            PL:
              2030: 35543.3e6
              2040: 23695.5e6
              2050: 11847.8e6
            SE:
              2030: 36603.3e6
              2040: 24402.2e6
              2050: 12201.1e6



  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9321
      2030: 0.8687
      2035: 0.7719
      2040: 0.6926
      2045: 0.6417
ref-constr01:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG
  solving:
    constraints:
      co2_budget_national:
        2020:
          DE: 0.668
        2025:
          DE: 0.521
        2030:
          DE: 0.351
        2035:
          DE: 0.217
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.046
  clever: false
  land_use_module:
    types:
      DLU:
        constraint:
          enable: true
          max_limit:
            AT:
              2030: 16407.2e6
              2040: 8326.0e6
              2050: 244.9e6
            BE:
              2030: 4745.5e6
              2040: 2408.2e6
              2050: 70.8e6
            CH:
              2030: 27.4e6
              2040: 13.9e6
              2050: 0.4e6
            CZ:
              2030: 12245.7e6
              2040: 6214.2e6
              2050: 182.8e6
            DE:
              2030: 54250.3e6
              2040: 27530.0e6
              2050: 809.7e6
            DK:
              2030: 5443.1e6
              2040: 2762.2e6
              2050: 81.2e6
            ES:
              2030: 19382.4e6
              2040: 9835.8e6
              2050: 289.3e6
            FR:
              2030: 38472.9e6
              2040: 19523.6e6
              2050: 574.2e6
            GB:
              2030: 19215.7e6
              2040: 9751.3e6
              2050: 286.8e6
            IT:
              2030: 27693.1e6
              2040: 14053.2e6
              2050: 413.3e6
            LU:
              2030: 404.7e6
              2040: 205.4e6
              2050: 6.0e6
            NL:
              2030: 6989.0e6
              2040: 3546.7e6
              2050: 104.3e6
            NO:
              2030: 3316.9e6
              2040: 1683.2e6
              2050: 49.5e6
            PL:
              2030: 31751.9e6
              2040: 16112.9e6
              2050: 473.9e6
            SE:
              2030: 32698.9e6
              2040: 16593.5e6
              2050: 488.0e6

  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9321
      2030: 0.8687
      2035: 0.7719
      2040: 0.6926
      2045: 0.6417
cle-constr50:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG
  solving:
    constraints:
      co2_budget_national:
        2020:
          DE: 0.668
        2025:
          DE: 0.521
        2030:
          DE: 0.351
        2035:
          DE: 0.217
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.046
  clever: true
  land_use_module:
    types:
      DLU:
        constraint:
          enable: true
          max_limit:
            AT:
              2030: 20407.0e6
              2040: 16325.6e6
              2050: 12244.2e6
            BE:
              2030: 5902.4e6
              2040: 4721.9e6
              2050: 3541.4e6
            CH:
              2030: 34.1e6
              2040: 27.3e6
              2050: 20.5e6
            CZ:
              2030: 15231.0e6
              2040: 12184.8e6
              2050: 9138.6e6
            DE:
              2030: 67475.5e6
              2040: 53980.4e6
              2050: 40485.3e6
            DK:
              2030: 6770.0e6
              2040: 5416.0e6
              2050: 4062.0e6
            ES:
              2030: 24107.4e6
              2040: 19285.9e6
              2050: 14464.5e6
            FR:
              2030: 47851.9e6
              2040: 38281.5e6
              2050: 28711.1e6
            GB:
              2030: 23900.2e6
              2040: 19120.1e6
              2050: 14340.1e6
            IT:
              2030: 34444.1e6
              2040: 27555.3e6
              2050: 20666.5e6
            LU:
              2030: 503.4e6
              2040: 402.7e6
              2050: 302.0e6
            NL:
              2030: 8692.8e6
              2040: 6954.2e6
              2050: 5215.7e6
            NO:
              2030: 4125.5e6
              2040: 3300.4e6
              2050: 2475.3e6
            PL:
              2030: 39492.5e6
              2040: 31594.0e6
              2050: 23695.5e6
            SE:
              2030: 40670.4e6
              2040: 32536.3e6
              2050: 24402.2e6

  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9321
      2030: 0.8687
      2035: 0.7719
      2040: 0.6926
      2045: 0.6417
cle-constr25:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG
  solving:
    constraints:
      co2_budget_national:
        2020:
          DE: 0.668
        2025:
          DE: 0.521
        2030:
          DE: 0.351
        2035:
          DE: 0.217
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.046
  clever: true
  land_use_module:
    types:
      DLU:
        constraint:
          enable: true
          max_limit:
            AT:
              2030: 18366.3e6
              2040: 12244.2e6
              2050: 6122.1e6
            BE:
              2030: 5312.1e6
              2040: 3541.4e6
              2050: 1770.7e6
            CH:
              2030: 30.7e6
              2040: 20.5e6
              2050: 10.2e6
            CZ:
              2030: 13707.9e6
              2040: 9138.6e6
              2050: 4569.3e6
            DE:
              2030: 60727.9e6
              2040: 40485.3e6
              2050: 20242.6e6
            DK:
              2030: 6093.0e6
              2040: 4062.0e6
              2050: 2031.0e6
            ES:
              2030: 21696.7e6
              2040: 14464.5e6
              2050: 7232.2e6
            FR:
              2030: 43066.7e6
              2040: 28711.1e6
              2050: 14355.6e6
            GB:
              2030: 21510.2e6
              2040: 14340.1e6
              2050: 7170.1e6
            IT:
              2030: 30999.7e6
              2040: 20666.5e6
              2050: 10333.2e6
            LU:
              2030: 453.1e6
              2040: 302.0e6
              2050: 151.0e6
            NL:
              2030: 7823.5e6
              2040: 5215.7e6
              2050: 2607.8e6
            NO:
              2030: 3712.9e6
              2040: 2475.3e6
              2050: 1237.6e6
            PL:
              2030: 35543.3e6
              2040: 23695.5e6
              2050: 11847.8e6
            SE:
              2030: 36603.3e6
              2040: 24402.2e6
              2050: 12201.1e6


  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9321
      2030: 0.8687
      2035: 0.7719
      2040: 0.6926
      2045: 0.6417
cle-constr01:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG
  solving:
    constraints:
      co2_budget_national:
        2020:
          DE: 0.668
        2025:
          DE: 0.521
        2030:
          DE: 0.351
        2035:
          DE: 0.217
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.046
  clever: true
  land_use_module:
    types:
      DLU:
        constraint:
          enable: true
          max_limit:
            AT:
              2030: 16407.2e6
              2040: 8326.0e6
              2050: 244.9e6
            BE:
              2030: 4745.5e6
              2040: 2408.2e6
              2050: 70.8e6
            CH:
              2030: 27.4e6
              2040: 13.9e6
              2050: 0.4e6
            CZ:
              2030: 12245.7e6
              2040: 6214.2e6
              2050: 182.8e6
            DE:
              2030: 54250.3e6
              2040: 27530.0e6
              2050: 809.7e6
            DK:
              2030: 5443.1e6
              2040: 2762.2e6
              2050: 81.2e6
            ES:
              2030: 19382.4e6
              2040: 9835.8e6
              2050: 289.3e6
            FR:
              2030: 38472.9e6
              2040: 19523.6e6
              2050: 574.2e6
            GB:
              2030: 19215.7e6
              2040: 9751.3e6
              2050: 286.8e6
            IT:
              2030: 27693.1e6
              2040: 14053.2e6
              2050: 413.3e6
            LU:
              2030: 404.7e6
              2040: 205.4e6
              2050: 6.0e6
            NL:
              2030: 6989.0e6
              2040: 3546.7e6
              2050: 104.3e6
            NO:
              2030: 3316.9e6
              2040: 1683.2e6
              2050: 49.5e6
            PL:
              2030: 31751.9e6
              2040: 16112.9e6
              2050: 473.9e6
            SE:
              2030: 32698.9e6
              2040: 16593.5e6
              2050: 488.0e6
  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9321
      2030: 0.8687
      2035: 0.7719
      2040: 0.6926
      2045: 0.6417
