# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT


8Gt_Bal_v3:

  land_use_module:
    constraint:
      enable: false



no_unsus_phaseout:

  biomass:
    share_unsustainable_use_retained:
      2020: 1
      2025: 1
      2030: 1
      2035: 1
      2040: 1
      2045: 1
      2050: 1
    share_sustainable_potential_available:  # default values
      2020: 0
      2025: 0.33
      2030: 0.66
      2035: 1
      2040: 1
      2045: 1
      2050: 1

  land_use_module:
    constraint:
      enable: false



constrained:

  land_use_module:
    constraint:
      enable: true
      max_limit:
        2020: 250e10
        2030: 250e10
        2040: 250e10
