# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT


8Gt_Bal_v3:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG

  solving:
    constraints:
      co2_budget_national:
        2020:
          DE: 0.668
        2025:
          DE: 0.521
        2030:
          DE: 0.351
        2035:
          DE: 0.217
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.046

  clever: false

  land_use_module:
    types:
      DLU:
        constraint:
          enable: false




  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9321
      2030: 0.8687
      2035: 0.7719
      2040: 0.6926
      2045: 0.6417
reference:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG

  solving:
    constraints:
      co2_budget_national:
        2020:
          DE: 0.668
        2025:
          DE: 0.521
        2030:
          DE: 0.351
        2035:
          DE: 0.217
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.046

  biomass:
    share_unsustainable_use_retained:
      2020: 1
      2025: 1
      2030: 1
      2035: 1
      2040: 1
      2045: 1
      2050: 1
    share_sustainable_potential_available:
      2020: 0
      2025: 0.33
      2030: 0.66
      2035: 1
      2040: 1
      2045: 1
      2050: 1
    share_unsustainable_min:
      2020: 1
      2025: 0.66
      2030: 0.33
      2035: 0
      2040: 0
      2045: 0
      2050: 0

  clever: false

  land_use_module:
    types:
      DLU:
        constraint:
          enable: false



  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9321
      2030: 0.8687
      2035: 0.7719
      2040: 0.6926
      2045: 0.6417
clever:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG

  solving:
    constraints:
      co2_budget_national:
        2020:
          DE: 0.668
        2025:
          DE: 0.521
        2030:
          DE: 0.351
        2035:
          DE: 0.217
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.046

  biomass:
    share_unsustainable_use_retained:
      2020: 1
      2025: 1
      2030: 1
      2035: 1
      2040: 1
      2045: 1
      2050: 1
    share_sustainable_potential_available:
      2020: 0
      2025: 0.33
      2030: 0.66
      2035: 1
      2040: 1
      2045: 1
      2050: 1
    share_unsustainable_min:
      2020: 1
      2025: 0.66
      2030: 0.33
      2035: 0
      2040: 0
      2045: 0
      2050: 0

  clever: true

  land_use_module:
    types:
      DLU:
        constraint:
          enable: false




  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9321
      2030: 0.8687
      2035: 0.7719
      2040: 0.6926
      2045: 0.6417
sr_DE10_EU5:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG

  solving:
    constraints:
      co2_budget_national:
        2020:
          DE: 0.668
        2025:
          DE: 0.521
        2030:
          DE: 0.351
        2035:
          DE: 0.217
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.046

  biomass:
    share_unsustainable_use_retained:
      2020: 0.5
      2025: 0.5
      2030: 0.45
      2035: 0.45
      2040: 0.4
      2045: 0.4
      2050: 0.4
    share_sustainable_potential_available:  # default values
      2020: 0.5
      2025: 0.5
      2030: 0.55
      2035: 0.55
      2040: 0.6
      2045: 0.6
      2050: 0.6
    share_unsustainable_min: # share of share_unsustainable_use_retained as minimum use
      2020: 0
      2025: 0
      2030: 0
      2035: 0
      2040: 0
      2045: 0
      2050: 0

  clever: false

  land_use_module:
    types:
      DLU:
        constraint:
          enable: true
          max_limit:  # unit in m²
            EU:  # for all countries and 5% of that area
              2020: 85e9 #171e9
              2030: 85e9 #171e9
              2040: 85e9 #171e9
            DE:
              2020: 31e9 #35.8e9  # 10% of Germany area
              2030: 31e9 #35.8e9
              2040: 31e9 #35.8e9
#            FR:
#              2020: 27.3e9  # 5% of France area
#              2030: 27.3e9
#              2040: 27.3e9

  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9321
      2030: 0.8687
      2035: 0.7719
      2040: 0.6926
      2045: 0.6417
