# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT


8Gt_Bal_v3:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG
  solving:
    constraints: { }

  clever: false

  land_use_module:
    types:
      DLU:
        constraint:
          enable: false

  biomass: # from config.default
    share_unsustainable_use_retained:
      2020: 1
      2025: 0.66
      2030: 0.33
      2035: 0
      2040: 0
      2045: 0
      2050: 0
    share_sustainable_potential_available:
      2020: 0
      2025: 0.33
      2030: 0.66
      2035: 1
      2040: 1
      2045: 1
      2050: 1
    share_unsustainable_min: # share of share_unsustainable_use_retained as minimum use
      2020: 1
      2025: 1
      2030: 1
      2035: 1
      2040: 1
      2045: 1
      2050: 1




reference:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG
  solving:
    constraints: { }


  clever: false

  land_use_module:
    types:
      DLU:
        constraint:
          enable: false



clever:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG
  solving:
    constraints: { }

  clever: true

  land_use_module:
    types:
      DLU:
        constraint:
          enable: false




ref-constr50:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG
  solving:
    constraints: { }

  clever: false

  land_use_module:
    types:
      DLU:
        constraint:
          enable: true
          max_limit:  # unit in m²
#            EU:
#              2020: 340e9
#              2030: 340e9
#              2040: 340e9
            DE:
              2020: 1e12
              2030: 8.261328e+10
              2040: 6.609062e+10
              2050: 4.956796e+10

cle-constr50:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG
  solving:
    constraints: { }

  clever: true

  land_use_module:
    types:
      DLU:
        constraint:
          enable: true
          max_limit:  # unit in m²
#            EU:
#              2020: 340e9
#              2030: 340e9
#              2040: 340e9
            DE:
              2020: 1e12
              2030: 8.261328e+10
              2040: 6.609062e+10
              2050: 4.956796e+10
