# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT


8Gt_Bal_v3:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG

  land_use_module:
    constraint:
      enable: false

  ### pypsa-de default configs
  costs:
    horizon: mean
    NEP: 2023
    transmission: overhead   # either overhead line ("overhead") or underground cable ("underground")

  solving:
    constraints:
      # boundary condition of maximum volumes
      limits_volume_max:
        # constrain electricity import in TWh
        electricity_import:
          DE:
            2020: -20
            2025: 0
            2030: 0
            2035: 40
            2040: 80
            2045: 125
        electrolysis:
          DE:
            2020: 0
            2025: 5
            2030: 45
            2035: 130
            2040: 215
            2045: 300
        h2_derivate_import:
          DE:
            2020: 0
            2025: 0
            2030: 10
            2035: 105
            2040: 200
            2045: 300
        h2_import:
          DE:
            2020: 0
            2025: 5
            2030: 15
            2035: 115
            2040: 220
            2045: 325
      limits_volume_min:
        electrolysis:
          DE:
            2020: 0
            2025: 0
            2030: 0
            2035: 0
            2040: 0
            2045: 0
      limits_capacity_min:
        Link:
          H2 Electrolysis:
            DE:
              2030: 5

      co2_budget_national:
        2020:
          DE: 0.668
        2025:
          DE: 0.521
        2030:
          DE: 0.351
        2035:
          DE: 0.217
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.046
  industry:
    steam_biomass_fraction: 0.4
    steam_hydrogen_fraction: 0.3
    steam_electricity_fraction: 0.3



  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9321
      2030: 0.8687
      2035: 0.7719
      2040: 0.6926
      2045: 0.6417
ENS_sus_unsus_share:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG

  biomass:
    share_unsustainable_use_retained:
      2020: 0.5
      2025: 0.5
      2030: 0.45
      2035: 0.45
      2040: 0.4
      2045: 0.4
      2050: 0.4
    share_sustainable_potential_available:  # default values
      2020: 0.5
      2025: 0.5
      2030: 0.55
      2035: 0.55
      2040: 0.6
      2045: 0.6
      2050: 0.6

  land_use_module:
    constraint:
      enable: false

  ### pypsa-de default configs
  costs:
    horizon: mean
    NEP: 2023
    transmission: overhead   # either overhead line ("overhead") or underground cable ("underground")

  solving:
    constraints:
      # boundary condition of maximum volumes
      limits_volume_max:
        # constrain electricity import in TWh
        electricity_import:
          DE:
            2020: -20
            2025: 0
            2030: 0
            2035: 40
            2040: 80
            2045: 125
        electrolysis:
          DE:
            2020: 0
            2025: 5
            2030: 45
            2035: 130
            2040: 215
            2045: 300
        h2_derivate_import:
          DE:
            2020: 0
            2025: 0
            2030: 10
            2035: 105
            2040: 200
            2045: 300
        h2_import:
          DE:
            2020: 0
            2025: 5
            2030: 15
            2035: 115
            2040: 220
            2045: 325
      limits_volume_min:
        electrolysis:
          DE:
            2020: 0
            2025: 0
            2030: 0
            2035: 0
            2040: 0
            2045: 0
      limits_capacity_min:
        Link:
          H2 Electrolysis:
            DE:
              2030: 5

      co2_budget_national:
        2020:
          DE: 0.668
        2025:
          DE: 0.521
        2030:
          DE: 0.351
        2035:
          DE: 0.217
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.046
  industry:
    steam_biomass_fraction: 0.4
    steam_hydrogen_fraction: 0.3
    steam_electricity_fraction: 0.3



  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9321
      2030: 0.8687
      2035: 0.7719
      2040: 0.6926
      2045: 0.6417
ENS_share_constrained:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG

  biomass:
    share_unsustainable_use_retained:
      2020: 0.5
      2025: 0.5
      2030: 0.45
      2035: 0.45
      2040: 0.4
      2045: 0.4
      2050: 0.4
    share_sustainable_potential_available:  # default values
      2020: 0.5
      2025: 0.5
      2030: 0.55
      2035: 0.55
      2040: 0.6
      2045: 0.6
      2050: 0.6

  land_use_module:
    constraint:
      enable: true
      max_limit:  # unit in m²
        EU:  # for all countries
          2020: 50e9
          2030: 50e9
          2040: 50e9
        DE:
          2020: 10.7e9  # 3% of Germany area
          2030: 10.7e9
          2040: 10.7e9
        FR:
          2020: 27.3e9  # 3% of France area
          2030: 27.3e9
          2040: 27.3e9

        DE3: # Berlin, 3%
          2020: 999e9 #26.7e6
          2030: 26.7e6
          2040: 26.7e6
        DE5: # Bremen, 1%
          2020: 999e9 #4.2e6
          2030: 4.2e6
          2040: 4.2e6
        DE6: # Hamburg, 1%
          2020: 999e9  #7.5e6
          2030: 7.5e6
          2040: 7.5e6
        #DEC:  # Saarland
        GBI: # London, 1%
          2020: 999e9  #15.7e6
          2030: 15.7e6
          2040: 15.7e6

  ### pypsa-de default configs
  costs:
    horizon: mean
    NEP: 2023
    transmission: overhead   # either overhead line ("overhead") or underground cable ("underground")

  solving:
    constraints:
      # boundary condition of maximum volumes
      limits_volume_max:
        # constrain electricity import in TWh
        electricity_import:
          DE:
            2020: -20
            2025: 0
            2030: 0
            2035: 40
            2040: 80
            2045: 125
        electrolysis:
          DE:
            2020: 0
            2025: 5
            2030: 45
            2035: 130
            2040: 215
            2045: 300
        h2_derivate_import:
          DE:
            2020: 0
            2025: 0
            2030: 10
            2035: 105
            2040: 200
            2045: 300
        h2_import:
          DE:
            2020: 0
            2025: 5
            2030: 15
            2035: 115
            2040: 220
            2045: 325
      limits_volume_min:
        electrolysis:
          DE:
            2020: 0
            2025: 0
            2030: 0
            2035: 0
            2040: 0
            2045: 0
      limits_capacity_min:
        Link:
          H2 Electrolysis:
            DE:
              2030: 5

      co2_budget_national:
        2020:
          DE: 0.668
        2025:
          DE: 0.521
        2030:
          DE: 0.351
        2035:
          DE: 0.217
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.046
  industry:
    steam_biomass_fraction: 0.4
    steam_hydrogen_fraction: 0.3
    steam_electricity_fraction: 0.3



  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9321
      2030: 0.8687
      2035: 0.7719
      2040: 0.6926
      2045: 0.6417
