# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT


8Gt_Bal_v3:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG
  solving:
    constraints:
      co2_budget_national:
        2020:
          DE: 0.668
        2025:
          DE: 0.521
        2030:
          DE: 0.351
        2035:
          DE: 0.217
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.046

  clever: false

  land_use_module:
    types:
      DLU:
        constraint:
          enable: false

  biomass: # from config.default
    share_unsustainable_use_retained:
      2020: 1
      2025: 0.66
      2030: 0.33
      2035: 0
      2040: 0
      2045: 0
      2050: 0
    share_sustainable_potential_available:
      2020: 0
      2025: 0.33
      2030: 0.66
      2035: 1
      2040: 1
      2045: 1
      2050: 1
    share_unsustainable_min: # share of share_unsustainable_use_retained as minimum use
      2020: 1
      2025: 1
      2030: 1
      2035: 1
      2040: 1
      2045: 1
      2050: 1




  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9321
      2030: 0.8687
      2035: 0.7719
      2040: 0.6926
      2045: 0.6417
reference:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG
  solving:
    constraints:
      co2_budget_national:
        2020:
          DE: 0.668
        2025:
          DE: 0.521
        2030:
          DE: 0.351
        2035:
          DE: 0.217
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.046


  clever: false

  land_use_module:
    types:
      DLU:
        constraint:
          enable: false



  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9321
      2030: 0.8687
      2035: 0.7719
      2040: 0.6926
      2045: 0.6417
clever:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG
  solving:
    constraints:
      co2_budget_national:
        2020:
          DE: 0.668
        2025:
          DE: 0.521
        2030:
          DE: 0.351
        2035:
          DE: 0.217
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.046

  clever: true

  land_use_module:
    types:
      DLU:
        constraint:
          enable: false




  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9321
      2030: 0.8687
      2035: 0.7719
      2040: 0.6926
      2045: 0.6417
ref-constr50:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG
  solving:
    constraints:
      co2_budget_national:
        2020:
          DE: 0.668
        2025:
          DE: 0.521
        2030:
          DE: 0.351
        2035:
          DE: 0.217
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.046

  clever: false

  land_use_module:
    types:
      DLU:
        constraint:
          enable: true
          max_limit:  # unit in m²
#            EU:
#              2020: 340e9
#              2030: 340e9
#              2040: 340e9
            DE:
              2020: 1e12
              2030: 8.261328e+10
              2040: 6.609062e+10
              2050: 4.956796e+10

  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9321
      2030: 0.8687
      2035: 0.7719
      2040: 0.6926
      2045: 0.6417
cle-constr50:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG
  solving:
    constraints:
      co2_budget_national:
        2020:
          DE: 0.668
        2025:
          DE: 0.521
        2030:
          DE: 0.351
        2035:
          DE: 0.217
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.046

  clever: true

  land_use_module:
    types:
      DLU:
        constraint:
          enable: true
          max_limit:  # unit in m²
#            EU:
#              2020: 340e9
#              2030: 340e9
#              2040: 340e9
            DE:
              2020: 1e12
              2030: 8.261328e+10
              2040: 6.609062e+10
              2050: 4.956796e+10
  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9321
      2030: 0.8687
      2035: 0.7719
      2040: 0.6926
      2045: 0.6417
